# Generated by Django 5.2.4 on 2025-08-06 04:00

import root.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='year',
            field=models.PositiveIntegerField(validators=[root.validators.validate_year]),
        ),
    ]
