# Generated by Django 5.2.4 on 2025-08-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_reportcard_year'),
        ('student', '0002_rename_date_ob_birth_student_date_of_birth'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'year'], name='report_repo_student_8e8f6c_idx'),
        ),
    ]
