# Generated by Django 5.2.4 on 2025-08-06 12:53

import root.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportcard_report_repo_student_8e8f6c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[root.validators.validate_score]),
        ),
    ]
