# Generated by Django 5.2.4 on 2025-08-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_ob_birth',
            new_name='date_of_birth',
        ),
    ]
